# These are supported funding model platforms

github: # madilraza
patreon:  madilraza
open_collective:  muhammad-adil-raza-malik
ko_fi: madilraza
tidelift:  madilraza
community_bridge: cloud-foundry
liberapay:  madilraza
issuehunt:  madilraza
otechie: madilraza
custom:   ['https://github.com/users/madilraza/projects/3', 'https://github.com/users/madilraza/projects/2']
